### ISSUE TITLE
Eline saglik

### ISSUE THREAD

**Issue by VB10** [tahaturan/ChatApp#1]
Yayinda reponu inceledim yorumlar ekledim bide senin icin uikit urettim istersen buna gore projeni guncllerisn

https://app.uizard.io/p/6f288bd4

<img width="877" alt="image" src="https://github.com/tahaturan/ChatApp/assets/17102578/74340e4a-3e9f-41e3-8019-0640f7cbd597">

**Comment by tahaturan** [comment]
Çok teşekkür ederim hocam sağolun.
